name: Update Daily ATR Levels

on:
  workflow_dispatch:  # Manual run option
  schedule:
    - cron: '0 1 * * 1-5'  # Run at 1:00 UTC on weekdays

jobs:
  update-atr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        - name: Checkout repository
  uses: actions/checkout@v3
  with:
    token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Run ATR Level Generator
        run: python scripts/generate_daily_atr_levels.py

      - name: Commit updated ATR levels
        env:
          GH_PAT: ${{ secrets.GH_PAT }}   # ← optional but clearer
        run: |
          git config user.name "tesrak-stats"
          git config user.email "github-actions@github.com"
          git add data/daily_atr_levels.json
          git commit -m "Update ATR levels automatically" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/tesrak-stats/atr-dashboard.git HEAD:main
